### ISSUE TITLE
TypeError: can't access property "headers", appContext.ctx.req is undefined

### ISSUE THREAD

**Issue by boriskirov** [taddison/next-password-protect-sample#3]
Hey I end up getting this response 

in pages/_app.js (21:8) @ _callee$ : `TypeError: can't access property "headers", appContext.ctx.req is undefined`

once I implement fully your project, not sure how to fix that? It works for example if I refresh the page.

**Comment by taddison** [comment]
This is normally because Next.js has used client-side routing, rather than sending a request to the server.  This can happen if you use the `next/link` component, rather than a regular anchor link (`<a href='...'>`).

This is called out in the accompanying blog post (not sure if you've seen - I could probably make it a little clearer!):
https://tjaddison.com/blog/2020/06/password-protect-a-nextjs-site-deployed-to-vercel/

> Note that we use `window.location.href` as the redirect must trigger a request to the server, and we don’t want Next to attempt to use client-side routing.

This isn't great - and I'd love to disable client-side routing more globally in `_App.js` (there may well be a way I'm not aware of).

If this isn't the problem you're facing please re-open this issue and share the steps you took to generate the error.
